### ISSUE TITLE
Players do not start with the starting value configured...

### ISSUE THREAD

**Issue by graysonlee123** [TheNewEconomy/HellConomy#1]

**Comment by graysonlee123** [comment]
https://pastebin.com/W9VfNhjW

**Comment by graysonlee123** [comment]
Also wanted to mention the '75' has been tried as both '75' and '$75'

**Comment by creatorfromhell** [comment]
Please use the correct format, it's not there to be optional. In fact, you had to delete the format to post a blank issue.

**Comment by creatorfromhell** [comment]
I'll look at this. HellConomy is really not the main project so this may take some time as this takes a back seat to The New Economy ( https://www.spigotmc.org/resources/the-new-economy.7805/ )
